#! /bin/bash

output="$1"

set -x

exec 3>"$output"

cat >&3 <<EOF
% Generated by build_table1.sh
\begin{tabular}{llllll}
Test name              & Static analysis         & \multicolumn{2}{l}{Generating candidate bugs} & Building enforcer  & Building fix \\\\
                       &                         & From core dump & Ab initio                    &                    &              \\\\
\hline
EOF

summarise_dist() {
    t=$(mktemp)
    <"$1" discard_outliers.py 0.05 | check_dist > "$t"
    mu=$(<"$t" grep "pop stats" | sed 's/.* mean = \([-0-9.]*\), sd =.*/\1/')
    sigma=$(<"$t" grep "pop stats" | sed 's/.* sd = \([-0-9.]*\), skew =.*/\1/')
    if grep -q "Cannot reject normality" "$t"
    then
	norm_warn=""
    else
	norm_warn=", not Gaussian"
    fi
    ./tests/minimal_direct/sane_round.py "$mu" "$sigma" > "$t"
    < "$t" read mu sigma
    echo -n "\$$mu \pm $sigma\$s${norm_warn}"
    rm -f "$t"
}

cat tests/minimal_direct/bug_table.txt | while read exe_name exe_descr nr_bugs
do
    make md_test_dir/${exe_name}.db.timing
    make md_test_dir/${exe_name}.build_summary_time
    for i in `seq 0 $(($nr_bugs - 1))`
    do
	make md_test_dir/${exe_name}~${i}.build_interp_time
	make md_test_dir/${exe_name}~${i}.build_fix_time
    done
    db_dist=$(summarise_dist md_test_dir/${exe_name}.db.timing)
    summary_dist=$(summarise_dist md_test_dir/${exe_name}.build_summary_time)

    printf "%-22s & %-20s &        & %-20s & " "$exe_descr" "$db_dist" "$summary_dist" >&3
    if [ "$nr_bugs" = 1 ]
    then
	interp_dist=$(summarise_dist md_test_dir/${exe_name}~0.build_interp_time)
	fix_dist=$(summarise_dist md_test_dir/${exe_name}~0.build_fix_time)
	printf "%-20s & %-20s \\\\\\\\\n" "${interp_dist}" "${fix_dist}" >&3
    else
	echo "\\\\" >&3
	for i in `seq 0 $(($nr_bugs - 1))`
	do
	    interp_dist=$(summarise_dist md_test_dir/${exe_name}~${i}.build_interp_time)
	    fix_dist=$(summarise_dist md_test_dir/${exe_name}~${i}.build_fix_time)
	    printf "%-22s & & & & %-20s & %-20s \\\\\\\\\n" "\hspace{20pt}Bug $i" "${interp_dist}" "${fix_dist}" >&3
	done
    fi
done

echo "\end{tabular}" >&3
