#! /bin/sh

binary="$1"
# Canonicalised types table
types="$2"
callgraph="$3"
# One of the machine directories generated by minimal_direct when
# CONFIG_RECORD_MACHINE_OPTIMISATIONS is set.
dir="$4"

set -x

../cross_check_machines "$binary" "$types" "$callgraph" "${dir}/pre_machine" "${dir}/pre_mai" "${dir}/post_machine" "${dir}/post_mai" "${dir}/opt"
